// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	versioned "github.frg.tech/cloud/fanplane/pkg/apis/client/clientset/versioned"
	internalinterfaces "github.frg.tech/cloud/fanplane/pkg/apis/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.frg.tech/cloud/fanplane/pkg/apis/client/listers/fanplane/v1alpha1"
	fanplane_v1alpha1 "github.frg.tech/cloud/fanplane/pkg/apis/fanplane/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EnvoyBootstrapInformer provides access to a shared informer and lister for
// EnvoyBootstraps.
type EnvoyBootstrapInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EnvoyBootstrapLister
}

type envoyBootstrapInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEnvoyBootstrapInformer constructs a new informer for EnvoyBootstrap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEnvoyBootstrapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEnvoyBootstrapInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEnvoyBootstrapInformer constructs a new informer for EnvoyBootstrap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEnvoyBootstrapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FanplaneV1alpha1().EnvoyBootstraps(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FanplaneV1alpha1().EnvoyBootstraps(namespace).Watch(options)
			},
		},
		&fanplane_v1alpha1.EnvoyBootstrap{},
		resyncPeriod,
		indexers,
	)
}

func (f *envoyBootstrapInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEnvoyBootstrapInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *envoyBootstrapInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fanplane_v1alpha1.EnvoyBootstrap{}, f.defaultInformer)
}

func (f *envoyBootstrapInformer) Lister() v1alpha1.EnvoyBootstrapLister {
	return v1alpha1.NewEnvoyBootstrapLister(f.Informer().GetIndexer())
}
