// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EnvoyBootstrapListerExpansion allows custom methods to be added to
// EnvoyBootstrapLister.
type EnvoyBootstrapListerExpansion interface{}

// EnvoyBootstrapNamespaceListerExpansion allows custom methods to be added to
// EnvoyBootstrapNamespaceLister.
type EnvoyBootstrapNamespaceListerExpansion interface{}

// GatewayListerExpansion allows custom methods to be added to
// GatewayLister.
type GatewayListerExpansion interface{}

// GatewayNamespaceListerExpansion allows custom methods to be added to
// GatewayNamespaceLister.
type GatewayNamespaceListerExpansion interface{}
