---
apiVersion: v1
kind: Namespace
metadata:
  name: fanplane
  labels:
    istio-injection: disabled
  annotations:
    iam.amazonaws.com/allowed-roles: |
      ["deny/*"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.fanplane.io
spec:
  scope: cluster-scoped
  group: fanplane.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: Gateway
    plural: gateways
    shortNames:
    - egt
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: envoybootstraps.fanplane.io
spec:
  group: fanplane.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: cluster-scoped
  names:
    kind: EnvoyBootstrap
    plural: envoybootstraps
    shortNames:
    - eb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkite-fanplane-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: fanplane
  name: fanplane-role
rules:
- apiGroups: ["fanplane.io"] # "" indicates the core API group
  resources: ["envoybootstraps", "gateways"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fanplane-role
subjects:
- kind: User
  name: system:serviceaccount:fanplane:buildkite-fanplane-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: fanplane-role
  apiGroup: rbac.authorization.k8s.io
