// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "github.frg.tech/cloud/fanplane/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.frg.tech/cloud/fanplane/pkg/apis/fanplane/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EnvoyBootstrapsGetter has a method to return a EnvoyBootstrapInterface.
// A group's client should implement this interface.
type EnvoyBootstrapsGetter interface {
	EnvoyBootstraps(namespace string) EnvoyBootstrapInterface
}

// EnvoyBootstrapInterface has methods to work with EnvoyBootstrap resources.
type EnvoyBootstrapInterface interface {
	Create(*v1alpha1.EnvoyBootstrap) (*v1alpha1.EnvoyBootstrap, error)
	Update(*v1alpha1.EnvoyBootstrap) (*v1alpha1.EnvoyBootstrap, error)
	UpdateStatus(*v1alpha1.EnvoyBootstrap) (*v1alpha1.EnvoyBootstrap, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EnvoyBootstrap, error)
	List(opts v1.ListOptions) (*v1alpha1.EnvoyBootstrapList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EnvoyBootstrap, err error)
	EnvoyBootstrapExpansion
}

// envoyBootstraps implements EnvoyBootstrapInterface
type envoyBootstraps struct {
	client rest.Interface
	ns     string
}

// newEnvoyBootstraps returns a EnvoyBootstraps
func newEnvoyBootstraps(c *FanplaneV1alpha1Client, namespace string) *envoyBootstraps {
	return &envoyBootstraps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the envoyBootstrap, and returns the corresponding envoyBootstrap object, and an error if there is any.
func (c *envoyBootstraps) Get(name string, options v1.GetOptions) (result *v1alpha1.EnvoyBootstrap, err error) {
	result = &v1alpha1.EnvoyBootstrap{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("envoybootstraps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EnvoyBootstraps that match those selectors.
func (c *envoyBootstraps) List(opts v1.ListOptions) (result *v1alpha1.EnvoyBootstrapList, err error) {
	result = &v1alpha1.EnvoyBootstrapList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("envoybootstraps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested envoyBootstraps.
func (c *envoyBootstraps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("envoybootstraps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a envoyBootstrap and creates it.  Returns the server's representation of the envoyBootstrap, and an error, if there is any.
func (c *envoyBootstraps) Create(envoyBootstrap *v1alpha1.EnvoyBootstrap) (result *v1alpha1.EnvoyBootstrap, err error) {
	result = &v1alpha1.EnvoyBootstrap{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("envoybootstraps").
		Body(envoyBootstrap).
		Do().
		Into(result)
	return
}

// Update takes the representation of a envoyBootstrap and updates it. Returns the server's representation of the envoyBootstrap, and an error, if there is any.
func (c *envoyBootstraps) Update(envoyBootstrap *v1alpha1.EnvoyBootstrap) (result *v1alpha1.EnvoyBootstrap, err error) {
	result = &v1alpha1.EnvoyBootstrap{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("envoybootstraps").
		Name(envoyBootstrap.Name).
		Body(envoyBootstrap).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *envoyBootstraps) UpdateStatus(envoyBootstrap *v1alpha1.EnvoyBootstrap) (result *v1alpha1.EnvoyBootstrap, err error) {
	result = &v1alpha1.EnvoyBootstrap{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("envoybootstraps").
		Name(envoyBootstrap.Name).
		SubResource("status").
		Body(envoyBootstrap).
		Do().
		Into(result)
	return
}

// Delete takes name of the envoyBootstrap and deletes it. Returns an error if one occurs.
func (c *envoyBootstraps) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("envoybootstraps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *envoyBootstraps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("envoybootstraps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched envoyBootstrap.
func (c *envoyBootstraps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EnvoyBootstrap, err error) {
	result = &v1alpha1.EnvoyBootstrap{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("envoybootstraps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
