version: 2
jobs:
  build:
    environment:
      http_proxy: http://proxy-dev.frg.tech:3128
      https_proxy: http://proxy-dev.frg.tech:3128
      no_proxy: "127.0.0.1,.frg.tech,.fanaticslabs.com"
    docker:
      - image: dockercore/golang-cross:1.11.0
    steps:
      - checkout 

      - restore_cache:
          keys:
            - fanplane-cache

      - run:
          name: Build
          command: |
            mkdir -p /tmp/docker
            export PKG_VERSION="1.${CIRCLE_BUILD_NUM}"
            echo "${PKG_VERSION}" > /tmp/docker/.version
            make setup
            make build
            cp ./fanplane /tmp/docker/fanplane

      - run:
          name: Test
          command: 
            make ci-test

      - store_test_results:
          path: reports
            
      - persist_to_workspace:
          root: /tmp/docker
          paths: 
            - .

      - store_artifacts:
          path: reports
          destination: raw-test-output

  deploy:
    docker:
      - image: docker.repo.frg.tech/ci-docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/docker
      - run:
          name: Deploy
          command: |
            cp /tmp/docker/fanplane .
            export PKG_VERSION=$(cat /tmp/docker/.version)
            docker login -u ${artifactory_user_id} -p ${artifactory_password} docker.repo.frg.tech
            docker-compose build 
            docker-compose push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
