---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    istio-injection: disabled
  annotations:
    iam.amazonaws.com/allowed-roles: |
      ["deny/*"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.fanplane.io
spec:
  scope: Namespaced
  group: fanplane.io
  version: v1alpha1
  names:
    kind: Gateway
    plural: gateways
    shortNames:
    - egt
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: envoybootstraps.fanplane.io
spec:
  group: fanplane.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: EnvoyBootstrap
    plural: envoybootstraps
    shortNames:
    - eb
