# To service account contacts kubernetes api is required that the api server is able to be contacted from infra
{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fanplane-role
rules:
- apiGroups: ["fanplane.io"] # "" indicates the core API group
  resources: ["envoybootstraps", "gateways"]
  verbs: ["*"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fanplane-clusterrole
subjects:
- kind: User
  name: system:serviceaccount:default:{{ .Values.serviceAccount.name }}
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: fanplane-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fanplane-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: fanplane-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

