// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.frg.tech/cloud/fanplane/pkg/apis/client/clientset/versioned/typed/fanplane/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFanplaneV1alpha1 struct {
	*testing.Fake
}

func (c *FakeFanplaneV1alpha1) EnvoyBootstraps(namespace string) v1alpha1.EnvoyBootstrapInterface {
	return &FakeEnvoyBootstraps{c, namespace}
}

func (c *FakeFanplaneV1alpha1) Gateways(namespace string) v1alpha1.GatewayInterface {
	return &FakeGateways{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFanplaneV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
